### ISSUE TITLE
这样做有什么好处呢？

### ISSUE THREAD

**Issue by NicholeGit** [charleyw/wechat-weapp-redux#1]

**Comment by charleyw** [comment]
你的这个问题太大了。建议你先去了解一下相关的内容，自己先考虑一下，再问这种问题。
Redux的链接：[redux](https://github.com/reactjs/redux) 
Google关于Redux的内容：[Google搜索Redux](https://www.google.com.sg/?gfe_rd=cr&ei=KMDtV_XUGYjM8ged05rgDQ#q=redux)
