### ISSUE TITLE
package.json里build的文件名和npm安装的不一致

### ISSUE THREAD

**Issue by xuming314** [charleyw/wechat-weapp-redux#6]
package.json里build的目标文件名是wechat-weapp-redux
而npm后的目标文件名是wechat-app-redux
建议把package.json里的build设置改成和npm一致。

**Comment by charleyw** [comment]
我检查了一下，好像没有发现这个问题唉。
唯独有区别的地方是在webpack的配置中。

而且我感觉用wechat-app-*这样的前缀会有歧义，感觉好像是微信的App本体。

**Comment by xuming314** [comment]
https://www.npmjs.com/package/wechat-app-redux
这个npm不是你的？说明文件和你的github一模一样。
如果那个npm不是你的，建议推送到npm，这样安装起来方便。
目前微信小程序我们都是通过npm安装大量三方库和用到ES6/ES7语法，
然后通过webpack压缩打包到微信开发者工具所需目录，通过soucemap还原调试；
所以制作npm类库包非常有必要。

**Comment by charleyw** [comment]
应该是有人把我代码拿过去 发布到NPM了

**Comment by charleyw** [comment]
我等之后有空发布上去

**Comment by charleyw** [comment]
https://www.npmjs.com/package/wechat-weapp-redux

**Comment by xuming314** [comment]
npm安装完后，package.json里，"main": "lib/index.js"找不到。lib目录没有上传。
导致require('wechat-weapp-redux')引用失败。
