### ISSUE TITLE
package.json里"main": "lib/index.js"找不到，导致require('wechat-weapp-redux')引用失败。

### ISSUE THREAD

**Issue by xuming314** [charleyw/wechat-weapp-redux#7]
npm安装完后，package.json里，"main": "lib/index.js"找不到, 导致require('wechat-weapp-redux')引用失败。

**Comment by xuming314** [comment]
手动修改main:src/index.js，
webpack报警告：
/app.js from UglifyJs
Unexpected token: name (Provider) [/src/~/.0.1.0@wechat-weapp-redux/src/index.js:1,0]

**Comment by charleyw** [comment]
你小程序用的是什么构建流程，能给我推荐一下不。我好本地测试一下。

**Comment by xuming314** [comment]
package.json里，"main"改成"bin/wechat-weapp-redux.js"好了。
默认require('wechat-weapp-redux.js')是找pakcage.json里main入口的。

**Comment by xuming314** [comment]
我小程序因为要用到es7/redux，所以是通过webpack打包压缩后再提供给“微信Web开发者工具”上传发布的。

**Comment by charleyw** [comment]
我上传了一个新的版本，你重新安装一下。

**Comment by xuming314** [comment]
安装了，可以使用，谢谢。
